version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: hovren/kontiki:build

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: Build extensions
          command: |
            cd python
            python3 setup.py build

      - run:
          name: Build wheel
          command: |
            cd python
            python3 setup.py bdist_wheel

      - store_artifacts:
          path: python/dist

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            python3 -m pytest python/tests

      #- store_artifacts:
      #    path: test-reports
      #    destination: test-reports