version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: hovren/kontiki:build

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: Build Kontiki Python package
          command: |
            cd python
            python3 setup.py build

      - run:
          name: Build wheel
          command: |
            cd python
            python3 setup.py bdist_wheel

      - store_artifacts:
          path: python/dist
          destination: dist

      - persist_to_workspace:
          root: .
          paths:
            - python/tests
            - python/dist
            - docs

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Install wheel
          command: |
            pip3 install python/dist/*.whl

      - run:
          name: Run tests
          command: |
            python3 -m pytest python/tests

  docs:
      <<: *defaults
      steps:
        - attach_workspace:
            at: .

        - run:
            name: Install wheel
            command: |
              pip3 install python/dist/*.whl

        - run:
            name: Sphinx - Build HTML
            command: |
              cd docs
              make html

        - store_artifacts:
            path: docs/_build
            destination: documentation

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build